name: Helm update


on:
  workflow_call:
  workflow_dispatch:

jobs:
  verify-helm-changes:
    name: Verify if AKO helm charts needs updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AKO repo
        uses: actions/checkout@v4

      - name: Install YQ
        run: |
          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout Helm Repo
        run: |
          git clone https://github.com/mongodb/helm-charts.git helm-charts-cloned

      - name: Verify if CRDs were changed
        id: crd-check
        run: |
          HELM_CRDS_PATH="./helm-charts-cloned/charts/atlas-operator-crds/templates"

          filesToCopy=()
          for filename in ./bundle/manifests/atlas.mongodb.com_*.yaml; do
          absName="$(basename "$filename")"
          echo "Verifying file: ${filename}"
          if ! diff "$filename" ${HELM_CRDS_PATH}/"$absName"; then
          filesToCopy+=("$filename")
          fi
          done

          fLen=${#filesToCopy[@]}
          if [ "$fLen" -eq 0 ]; then
            echo "No CRD changes detected"
            exit 0
          fi

          echo "The following CRD changes detected:"
          for (( i=0; i < fLen; i++ )); do
            echo "${filesToCopy[$i]}"
          done

          for (( i=0; i < fLen; i++ )); do
            echo "Copying ${filesToCopy[$i]} to ${HELM_CRDS_PATH}/"
            cp "${filesToCopy[$i]}" ${HELM_CRDS_PATH}/
          done

      - name: Verify if RBAC were changed
        id: rbac-check
        run: |
          HELM_RBAC_FILE=../helm-charts-cloned/charts/atlas-operator/rbac.yaml

          yq '.spec.install.spec.clusterPermissions[0].rules' ./bundle/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml > rbac.yaml

          echo "Comparing RBAC for CSV to RBAC in AKO helm chart"
          if ! diff rbac.yaml "$HELM_RBAC_FILE"; then
            echo "Copying RBAC"
            cp rbac.yaml "$HELM_RBAC_FILE"
          else
            echo "No changes detected"
          fi

      - name: Create PR for helm-charts repo
        if: steps.crd-check || steps.rbac-check
        run: |
          cd ./helm-charts-cloned
          git add .
          git commit -m "[autogenerated] update CRDs ${{ github.event.number }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/mongodb/helm-charts.git "[autogenerated] update CRDs ${{ github.event.number }}"

