name: Helm update


on:
  workflow_call:
  workflow_dispatch:

jobs:
  verify-helm-changes:
    name: Verify if AKO helm charts needs updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AKO repo
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: 'true'

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout Helm Repo
        run: |
          git clone https://github.com/mongodb/helm-charts.git ./helm-charts-cloned
          ls -lah

      - name: Verify if CRDs were changed
        id: crd-check
        env:
          HELM_CRDS_PATH: "./helm-charts-cloned/charts/atlas-operator-crds/templates"
        run: |
          devbox run -- "make helm-upd-crds"

      - name: Verify if RBAC were changed
        id: rbac-check
        env:
          HELM_RBAC_FILE: "./helm-charts-cloned/charts/atlas-operator/rbac.yaml"
        run: |
          devbox run -- "make helm-upd-rbac"

      - name: Create PR for helm-charts repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./helm-charts-cloned

          if [[ -n $(git status --porcelain) ]]; then
            BRANCH_NAME=CRD-RBAC-changes-${{ github.run_id }}
            COMMIT_MSG="[autogenerated] update CRDs and RBAC ${{ github.run_id }}"
            echo "Changes detected. Creating PR"
            git checkout -b "${BRANCH_NAME}"
            git add .
            git commit -m "${COMMIT_MSG}"
            gh pr create -B main -H "${BRANCH_NAME}" --title "${COMMIT_MSG}" --body "${COMMIT_MSG}"
          fi
          echo "Nothing to commit"
